### ISSUE TITLE
Lambda Functions

### ISSUE THREAD

**Issue by HovhannesApinyan** [ClimateNetTumoLabs/lambda-functions#2]
Please add new repo for Lambda function 
ADD WIKI how to create API and API endpoint, how to connect that API to lambda function. 
Add lambda function code to this repo and convert all other tasks(That communicate with this repo) to this repo

**Comment by HovhannesApinyan** [comment]
**Task Update:**

- Repository `lambda-function` has been successfully created. You can access it [here](https://github.com/ClimateNetTumoLabs/lambda-functions).
- Documentation for the following topics has been completed and is now available:
  - **Creating AWS API Gateway**: Detailed guide on setting up and integrating an API Gateway with AWS Lambda. Access the documentation [here](https://github.com/ClimateNetTumoLabs/lambda-functions/wiki/Creating-AWS-API-Gateway).
  - **Creating AWS Lambda function**: Comprehensive instructions on developing and deploying Lambda functions. View the guide [here](https://github.com/ClimateNetTumoLabs/lambda-functions/wiki/Creating-AWS-Lambda-function).

**Comment by HovhannesApinyan** [comment]
**New Tasks for the `lambda-function` Repository:**

- [x] **Create Requirements Files:** Generate `requirements.txt` files for both `climate_net_api` and `data_to_rds` directories
- [x] **Develop an Executable File for ZIP Creation:** Create an executable script (e.g., a Bash or Python script) that automates the creation of ZIP files containing the Lambda function code and dependencies for function.
- [x] **Document the Usage of Executable Files:** Write comprehensive documentation on how to use the newly created executable file for generating ZIP files. This documentation should include step-by-step instructions, prerequisites, and any necessary configuration details.

**Comment by HovhannesApinyan** [comment]
@AlternativeFuture 

Please note the requested changes. [Link to the request](https://github.com/ClimateNetTumoLabs/lambda-functions/pull/4#pullrequestreview-1990998678)
